using Volo.Abp;

namespace MultiTenantProductManagementApp.EntityFrameworkCore;

public abstract class MultiTenantProductManagementAppEntityFrameworkCoreTestBase : MultiTenantProductManagementAppTestBase<MultiTenantProductManagementAppEntityFrameworkCoreTestModule>
{

}
