using MultiTenantProductManagementApp.EntityFrameworkCore;
using Xunit;

namespace MultiTenantProductManagementApp.EntityFrameworkCore;

public class MultiTenantProductManagementAppEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<MultiTenantProductManagementAppEntityFrameworkCoreFixture>
{

}
