using Xunit;
using MultiTenantProductManagementApp;

namespace MultiTenantProductManagementApp.EntityFrameworkCore;

[CollectionDefinition(MultiTenantProductManagementAppTestConsts.CollectionDefinitionName)]
public class MultiTenantProductManagementAppEntityFrameworkCoreCollection : ICollectionFixture<MultiTenantProductManagementAppEntityFrameworkCoreFixture>
{

}
