<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>ProductService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="9.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProductService.Application\ProductService.Application.csproj" />
  </ItemGroup>

</Project>
