using Volo.Abp;

namespace MultiTenantProductManagementApp.MongoDB;

public abstract class MultiTenantProductManagementAppMongoDbTestBase : MultiTenantProductManagementAppTestBase<MultiTenantProductManagementAppMongoDbTestModule>
{
}
