using MultiTenantProductManagementApp.Shared.Products;
using MultiTenantProductManagementApp.MongoDB;

namespace MultiTenantProductManagementApp.Application.Tests.Products;

public class ProductAppService_Integration_Tests :
 ProductAppService_Integration_Tests_Base<MultiTenantProductManagementAppMongoDbTestModule>
{
}
